use_frameworks!

platform :ios, '8.0'

target 'podTestController_Example' do
  pod 'podTestController', :path => '../'

  target 'podTestController_Tests' do
    inherit! :search_paths

    
  end
end
